spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${JDBC_DATABASE_URL}
#    url: jdbc:postgresql://${HOST}:${DB_PORT}/${DATABASE}
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME}
    password: ${PASSWORD}
