---

spring:
  application:
    name: app
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  profiles:
    default: development
  devtools:
    livereload:
      enabled: false

server:
  address: 0.0.0.0

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://7ba61e6b337305a58f73904abc1b32b2@o4508321785315328.ingest.de.sentry.io/4508321795539024
  traces-sample-rate: 1.0
